FROM ubuntu
WORKDIR /src
#update the repository sources list
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update

# Installing dependencies (flask, mysql, php, supervisor)
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y libmysqlclient-dev
RUN apt-get install -y supervisor
RUN apt-get install -y openssh-server
RUN apt-get install -y vim
RUN apt-get install -y net-tools
RUN apt-get install -y netcat
RUN apt-get install -y gcc
RUN apt-get install -y sudo 

#add admin user
RUN useradd -ms /bin/bash admin
RUN echo "admin:dandydons" | chpasswd
RUN chown admin:admin /home/admin
RUN chmod 755 /home/admin

#add sshd config
#dont allow root login with password
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
#allow admin login with password
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
#allow admin login with ssh key
RUN sed -i 's/#AuthorizedKeysFile/AuthorizedKeysFile/' /etc/ssh/sshd_config

#change root password
RUN echo "root:VTCyberIsGreatAndSummitWasSoMuchFun!" | chpasswd

RUN echo "[program:flask]\ncommand=python3 /src/main.py" > /etc/supervisor/conf.d/flask.conf
RUN echo "[program:ssh]\ncommand=/usr/sbin/sshd -D" > /etc/supervisor/conf.d/ssh.conf

# Install app dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

#Copying necessary files
COPY ./app/ .
COPY lister.c .

COPY root.txt /root/root.txt
#make only readable by root
RUN chmod 400 /root/root.txt

#compile lister.c
RUN gcc -o lister lister.c
#remove lister.c
RUN rm lister.c
#move lister to /home/admin
RUN mv lister /home/admin
#make lister setuid
RUN chown root /home/admin/lister
RUN chmod +s /home/admin/lister
RUN mv /home/admin/lister /tmp/lister
#remove admin groups sudoer rights
RUN sed -i '/^%admin ALL=(ALL) ALL$/d' /etc/sudoers

ENV FLASK_APP main.py
#permanantly set flag as env variable
RUN echo "export flag=\"SummitCTF{1nject10n_thr0u5h_55RF_1s_4w3s0m3}\"" >> /etc/bash.bashrc
ENV flag="SummitCTF{1nject10n_thr0u5h_55RF_1s_4w3s0m3}"

RUN mkdir /run/sshd

EXPOSE 5000
EXPOSE 22
CMD ["supervisord", "-n"]
